version: '3.8'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    deploy:
      resources:
        limits:
          cpus: '0.5'  # Limit to 0.5 CPU
          memory: 512M  # Limit to 512 MB
    networks:
      - budget-network
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana  # Persistent volume for dashboards, datasources, etc.
    deploy:
      resources:
        limits:
          cpus: '0.5'  # Limit to 0.5 CPU
          memory: 512M  # Limit to 512 MB
    networks:
      - budget-network
  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    ports:
      - "9100:9100"
    deploy:
      resources:
        limits:
          cpus: '0.25'  # Limit to 0.25 CPU
          memory: 256M  # Limit to 256 MB
    networks:
      - budget-network
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "8083:8080"
    deploy:
      resources:
        limits:
          cpus: '0.25'  # Limit to 0.25 CPU
          memory: 256M  # Limit to 256 MB
    networks:
      - budget-network
  budget-app:
    build: /home/slyma/canvas-app
    image: monitoring-budget-app-1
    ports:
      - "8082:80"
      - "8443:443"  # SSL port for HTTPS
    expose:
      - "443"
    volumes:
      - /home/slyma/canvas-app/certs:/etc/nginx/ssl  # SSL certificates
    deploy:
      resources:
        limits:
          cpus: '1.5'  # Higher limit due to load test demands
          memory: 1536M  # Increased memory for performance
    networks:
      - budget-network
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_pass
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - mysql
    deploy:
      resources:
        limits:
          cpus: '1.5'  # Higher limit for WordPress under load
          memory: 1536M  # Increased memory
    networks:
      - budget-network
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_pass
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '0.5'  # Moderate limit for MySQL
          memory: 512M  # Sufficient for WordPress database
    networks:
      - budget-network
  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    ports:
      - "9115:9115"
    deploy:
      resources:
        limits:
          cpus: '0.25'  # Low resource usage
          memory: 256M  # Minimal memory needs
    networks:
      - budget-network
volumes:
  mysql-data:  # Existing volume for MySQL
  grafana-data:  # New volume for Grafana persistence
networks:
  budget-network:
    external: true
